USE [adito_dev]
GO

/****** Object:  Table [dbo].[AP_KAFKA_QUEUE]    Script Date: 08.05.2025 18:00:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AP_KAFKA_QUEUE](
	[QUEUE_ID] [char](36) NOT NULL,
	[TABLE_NAME] [varchar](50) NOT NULL,
	[ACTION_NAME] [varchar](50) NOT NULL,
	[KEY_VALUE] [varchar](50) NOT NULL,
	[DATA] [nvarchar](max) NULL,
	[EVENT_TIME] [datetime] NULL,
	[ProcessingStatus] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[QUEUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[AP_KAFKA_QUEUE] ADD  DEFAULT (getdate()) FOR [EVENT_TIME]
GO


